/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package System;


import java.awt.Color;
import java.awt.Component;
import java.awt.print.PrinterException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author LENOVO
 */
public class Tampilan extends javax.swing.JFrame {
    
        double Ford = 26567;
        double BMW = 45876;
        double Porche = 85709;
        double Aston_Martin = 157883;

    /**
     * Creates new form Tampilan
     */
    public Tampilan() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanelTitle = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jCmbSelectACar = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSelectaCarYear = new javax.swing.JTextField();
        jSelectaCarCost = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jTFTax = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTFSubTotal = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTFTotal = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jCustomerID = new javax.swing.JLabel();
        jTFCustomerID = new javax.swing.JTextField();
        jTFFristname = new javax.swing.JTextField();
        jFirstName = new javax.swing.JLabel();
        jTFPostCode = new javax.swing.JTextField();
        jTFAddress = new javax.swing.JTextField();
        jPostCode = new javax.swing.JLabel();
        jTown = new javax.swing.JLabel();
        tanggal = new javax.swing.JLabel();
        jTFTown = new javax.swing.JTextField();
        jPekerjaan = new javax.swing.JComboBox();
        jCalendarCombo1 = new org.freixas.jcalendar.JCalendarCombo();
        jAddress1 = new javax.swing.JLabel();
        Pekerjaan = new javax.swing.JLabel();
        JenisKelamin = new javax.swing.JLabel();
        jRadioPria = new javax.swing.JRadioButton();
        jRadioWanita = new javax.swing.JRadioButton();
        jTxtKalender = new javax.swing.JTextField();
        jTxtJam = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jBtnTotal = new javax.swing.JButton();
        jBtnReset = new javax.swing.JButton();
        jBtnPrint = new javax.swing.JButton();
        jBtnExit = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTxfTradeInCarYear = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jCmbTradeInCar = new javax.swing.JComboBox();
        jTxfTradeInCarCost = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jReceipt = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jCbkStereoSystem = new javax.swing.JCheckBox();
        jCbkLeatherInterior = new javax.swing.JCheckBox();
        jCbkStandard = new javax.swing.JCheckBox();
        jCbkModified = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Car Dealer Management System");
        setAutoRequestFocus(false);
        setType(java.awt.Window.Type.POPUP);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanelTitle.setBackground(new java.awt.Color(60, 63, 64));
        jPanelTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180), 3));
        jPanelTitle.setForeground(new java.awt.Color(60, 63, 64));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(188, 188, 188));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Car Dealer Management System");

        javax.swing.GroupLayout jPanelTitleLayout = new javax.swing.GroupLayout(jPanelTitle);
        jPanelTitle.setLayout(jPanelTitleLayout);
        jPanelTitleLayout.setHorizontalGroup(
            jPanelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(31, 31, 31))
        );
        jPanelTitleLayout.setVerticalGroup(
            jPanelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(60, 63, 64));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180), 3));
        jPanel5.setForeground(new java.awt.Color(60, 63, 64));

        jCmbSelectACar.setBackground(new java.awt.Color(60, 63, 64));
        jCmbSelectACar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jCmbSelectACar.setForeground(new java.awt.Color(188, 188, 188));
        jCmbSelectACar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih Mobil", "Ford", "BMW", "Porche", "Aston_Martin" }));
        jCmbSelectACar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(188, 188, 188), 0));
        jCmbSelectACar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmbSelectACarActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(188, 188, 188));
        jLabel11.setText("Tahun");

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(188, 188, 188));
        jLabel12.setText("Harga");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCmbSelectACar, 0, 272, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jSelectaCarCost, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jSelectaCarYear))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jCmbSelectACar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jSelectaCarYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSelectaCarCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(60, 63, 64));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180), 3));
        jPanel6.setForeground(new java.awt.Color(60, 63, 64));

        jTFTax.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(188, 188, 188));
        jLabel13.setText("Pajak");

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(188, 188, 188));
        jLabel14.setText("Sub Total");

        jTFSubTotal.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(188, 188, 188));
        jLabel15.setText("Total");

        jTFTotal.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
                    .addComponent(jTFTax)
                    .addComponent(jTFSubTotal))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTFTax, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTFSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTFTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(60, 63, 64));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180), 3));
        jPanel7.setForeground(new java.awt.Color(60, 63, 64));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(188, 188, 188));
        jLabel2.setText("Costumer Details");

        jCustomerID.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jCustomerID.setForeground(new java.awt.Color(188, 188, 188));
        jCustomerID.setText("Nomor KTP");

        jFirstName.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jFirstName.setForeground(new java.awt.Color(188, 188, 188));
        jFirstName.setText("Nama Lengkap");

        jPostCode.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jPostCode.setForeground(new java.awt.Color(188, 188, 188));
        jPostCode.setText("Kode Pos");

        jTown.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jTown.setForeground(new java.awt.Color(188, 188, 188));
        jTown.setText("Kota");

        tanggal.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        tanggal.setForeground(new java.awt.Color(188, 188, 188));
        tanggal.setText("Tanggal");

        jPekerjaan.setBackground(new java.awt.Color(60, 63, 64));
        jPekerjaan.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jPekerjaan.setForeground(new java.awt.Color(188, 188, 188));
        jPekerjaan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PNS", "Pegawai Swasta", "Wiraswasta", "Guru Honorer", "Petani", "Lainnya" }));

        jCalendarCombo1.setBorder(null);
        jCalendarCombo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCalendarCombo1ActionPerformed(evt);
            }
        });

        jAddress1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jAddress1.setForeground(new java.awt.Color(188, 188, 188));
        jAddress1.setText("Alamat");

        Pekerjaan.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Pekerjaan.setForeground(new java.awt.Color(188, 188, 188));
        Pekerjaan.setText("Pekerjaan");

        JenisKelamin.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        JenisKelamin.setForeground(new java.awt.Color(188, 188, 188));
        JenisKelamin.setText("Jenis Kelamin");

        buttonGroup1.add(jRadioPria);
        jRadioPria.setText("Pria");
        jRadioPria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioPriaActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioWanita);
        jRadioWanita.setText("Wanita");

        jTxtKalender.setBackground(new java.awt.Color(60, 63, 64));
        jTxtKalender.setForeground(new java.awt.Color(60, 63, 64));
        jTxtKalender.setBorder(null);
        jTxtKalender.setCaretColor(new java.awt.Color(60, 63, 64));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTxtKalender, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTxtJam, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFirstName)
                            .addComponent(JenisKelamin)
                            .addComponent(jCustomerID))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFFristname, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioPria)
                            .addComponent(jRadioWanita))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jAddress1)
                                .addGap(33, 33, 33)
                                .addComponent(jTFAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPostCode)
                                    .addComponent(tanggal))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jCalendarCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(jTFPostCode, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Pekerjaan)
                            .addComponent(jTown))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jTFTown)
                                .addGap(47, 47, 47))
                            .addComponent(jPekerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTxtKalender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTxtJam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCustomerID)
                            .addComponent(jTFCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFFristname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFirstName))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JenisKelamin)
                            .addComponent(jRadioPria)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jPostCode)
                                    .addComponent(jTFPostCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tanggal)
                                    .addComponent(jCalendarCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                    .addComponent(jAddress1)
                                    .addGap(2, 2, 2))
                                .addComponent(jTFAddress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGap(52, 52, 52)
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jPekerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Pekerjaan)))
                                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTown)
                                        .addComponent(jTFTown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(3, 3, 3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioWanita)
                .addGap(10, 10, 10))
        );

        jPanel9.setBackground(new java.awt.Color(60, 63, 64));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180), 3));
        jPanel9.setForeground(new java.awt.Color(60, 63, 64));

        jBtnTotal.setBackground(new java.awt.Color(60, 62, 64));
        jBtnTotal.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jBtnTotal.setForeground(new java.awt.Color(188, 188, 188));
        jBtnTotal.setText("Total");
        jBtnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnTotalActionPerformed(evt);
            }
        });

        jBtnReset.setBackground(new java.awt.Color(60, 62, 64));
        jBtnReset.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jBtnReset.setForeground(new java.awt.Color(188, 188, 188));
        jBtnReset.setText("Reset");
        jBtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnResetActionPerformed(evt);
            }
        });

        jBtnPrint.setBackground(new java.awt.Color(60, 62, 64));
        jBtnPrint.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jBtnPrint.setForeground(new java.awt.Color(188, 188, 188));
        jBtnPrint.setText("Print");
        jBtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPrintActionPerformed(evt);
            }
        });

        jBtnExit.setBackground(new java.awt.Color(60, 62, 64));
        jBtnExit.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jBtnExit.setForeground(new java.awt.Color(188, 188, 188));
        jBtnExit.setText("Exit");
        jBtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jBtnTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(60, 63, 64));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180), 3));

        jTxfTradeInCarYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxfTradeInCarYearActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(188, 188, 188));
        jLabel16.setText("Tahun");

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(188, 188, 188));
        jLabel17.setText("Harga");

        jCmbTradeInCar.setBackground(new java.awt.Color(60, 63, 64));
        jCmbTradeInCar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jCmbTradeInCar.setForeground(new java.awt.Color(188, 188, 188));
        jCmbTradeInCar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Jual Mobil", "1 - 5000", "5001 - 20000", "20001 - 50000", "50001 - 100000", "100001 - 500000" }));
        jCmbTradeInCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmbTradeInCarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCmbTradeInCar, 0, 264, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTxfTradeInCarCost)
                                .addGap(1, 1, 1))
                            .addComponent(jTxfTradeInCarYear))))
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jCmbTradeInCar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTxfTradeInCarYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jTxfTradeInCarCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(60, 62, 64));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(188, 188, 188), 3));

        jReceipt.setColumns(20);
        jReceipt.setRows(5);
        jScrollPane1.setViewportView(jReceipt);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(60, 62, 64));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(188, 188, 188), 3));

        jCbkStereoSystem.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jCbkStereoSystem.setText("Stereo System");

        jCbkLeatherInterior.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jCbkLeatherInterior.setText("Leather Interior");

        jCbkStandard.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jCbkStandard.setText("Standard");

        jCbkModified.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jCbkModified.setText("Modified");

        jCheckBox5.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jCheckBox5.setText("GPS");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCbkStereoSystem)
                    .addComponent(jCbkLeatherInterior)
                    .addComponent(jCbkStandard)
                    .addComponent(jCbkModified)
                    .addComponent(jCheckBox5))
                .addContainerGap(166, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCbkStereoSystem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCbkLeatherInterior)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCbkStandard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCbkModified)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 912, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(299, 299, 299)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
         this.getContentPane().setBackground(Color.darkGray);
         oCar car = new oCar();
         
//         jCmbTradeInCar.addItem(car.getTrade_in_1());
//         jCmbTradeInCar.addItem(car.getTrade_in_2());
//         jCmbTradeInCar.addItem(car.getTrade_in_3());
//         jCmbTradeInCar.addItem(car.getTrade_in_4());
//         jCmbTradeInCar.addItem(car.getTrade_in_5());
         
         
         jCbkStereoSystem.setSelected(true);
         jCbkLeatherInterior.setSelected(true);
         jCbkStandard.setSelected(true);
         jCbkModified.setSelected(true);
         jCheckBox5.setSelected(true);
    }//GEN-LAST:event_formWindowActivated

    private void jBtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExitActionPerformed
        // TODO add your handling code here:
        
        oCustomer iExit = new oCustomer();
        
        try{
            iExit.iExitSystem();
        } catch (NumberFormatException e){
            JOptionPane.showConfirmDialog(null, "Confirm If you want to Exit");
        }
    }//GEN-LAST:event_jBtnExitActionPerformed
private JFrame frame1;

    private void jBtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnResetActionPerformed
        // TODO add your handling code here:
         
         frame1 = new JFrame("Reset");
        
        if (JOptionPane.showConfirmDialog(frame1, "Confirm if you want to reset", "Car Dealer Management System", 
                JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION) {
            JTextField cleartext = null;
        
        try {
            for (Component c:jPanel7.getComponents()) {
            if (c.getClass().toString().contains("javax.swing.JTextField")){
                cleartext = (JTextField)c;
                cleartext.getText();
                jReceipt.setText("");
                jTFTax.setText("");
                jTFSubTotal.setText("");
                jTFTotal.setText("");
                jSelectaCarYear.setText("");
                jSelectaCarCost.setText("");
                jTxfTradeInCarYear.setText("");
                jTxfTradeInCarCost.setText("");
                jCmbSelectACar.setSelectedItem("Select a Car");
                jCmbTradeInCar.setSelectedItem("Trade in Car");
                jCbkStereoSystem.setSelected(false);
                jCbkLeatherInterior.setSelected(false);
                jCbkStandard.setSelected(false);
                jCbkModified.setSelected(false);
                jCheckBox5.setSelected(false);
                
            }}} catch (NumberFormatException e){
            JOptionPane.showConfirmDialog(null, "Confirm If you want to Reset");
        }
        
        
        
            
        }
       
    }//GEN-LAST:event_jBtnResetActionPerformed

    private void jBtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPrintActionPerformed
        // TODO add your handling code here:
        
        try {
            jReceipt.print();
        } catch (PrinterException ex) {
            Logger.getLogger(Tampilan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBtnPrintActionPerformed

    private void jCmbSelectACarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmbSelectACarActionPerformed
        // TODO add your handling code here:
        
        double Ford = 26567;
        double BMW = 45876;
        double Porche = 85709;
        double Aston_Martin = 157883;
        
        if (jCmbSelectACar.getSelectedItem().equals("Ford")){
            String Car = String.format("Rp %.2f", Ford);
            jSelectaCarCost.setText(Car);
            jSelectaCarYear.setText("2018");
        }
        
        if (jCmbSelectACar.getSelectedItem().equals("BMW")){
            String Car = String.format("£ %.2f", BMW);
            jSelectaCarCost.setText(Car);
            jSelectaCarYear.setText("2018");
        }
        
        if (jCmbSelectACar.getSelectedItem().equals("Porche")){
            String Car = String.format("£ %.2f", Porche);
            jSelectaCarCost.setText(Car);
            jSelectaCarYear.setText("2018");
        }
        
        if (jCmbSelectACar.getSelectedItem().equals("Aston_Martin")){
            String Car = String.format("£ %.2f", Aston_Martin);
            jSelectaCarCost.setText(Car);
            jSelectaCarYear.setText("2018");
        }
    }//GEN-LAST:event_jCmbSelectACarActionPerformed

    private void jCmbTradeInCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmbTradeInCarActionPerformed
        // TODO add your handling code here:
        
        
        if (jCmbTradeInCar.getSelectedItem().equals("1 - 5000")){
            jTxfTradeInCarCost.setText("5000");
            jTxfTradeInCarYear.setText("2018");
        }
        
        if (jCmbTradeInCar.getSelectedItem().equals("5001 - 20000")){
            jTxfTradeInCarCost.setText("2500");
            jTxfTradeInCarYear.setText("2018");
        }
        
        if (jCmbTradeInCar.getSelectedItem().equals("20001 - 50000")){
            jTxfTradeInCarCost.setText("2000");
            jTxfTradeInCarYear.setText("2018");
        }
        
        if (jCmbTradeInCar.getSelectedItem().equals("50001 - 100000")){
            jTxfTradeInCarCost.setText("1200");
            jTxfTradeInCarYear.setText("2018");
        }
        
        if (jCmbTradeInCar.getSelectedItem().equals("100001 - 500000")){
            jTxfTradeInCarCost.setText("250");
            jTxfTradeInCarYear.setText("2018");
        }
    }//GEN-LAST:event_jCmbTradeInCarActionPerformed
    
    public void jenKel(){
        
    }
    
    public double mcTax = 0.10;
    public Double cFindTax(double cAmount){
        double FindTax = (cAmount * mcTax);
        return FindTax;
    }
    private void jBtnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnTotalActionPerformed
        
        // ===============================================================================================================
        Car_Accessory Accessory = new Car_Accessory();
        
        //=================================================Ford===============================================================
        if (jCmbSelectACar.getSelectedItem().equals("Ford") && jCmbTradeInCar.getSelectedItem().equals("1 - 5000")){
            Ford = Ford - 5000;
            String iTax = String.format("£ %.2f", cFindTax(Ford + Accessory.GetAmount()));
            String iSubTotal = String.format("£ %.2f", Ford + Accessory.GetAmount());
            String iTotal = String.format("£ %.2f", Ford + Accessory.GetAmount() + cFindTax(Ford + Accessory.GetAmount()));
            jTFTax.setText(iTax);
            jTFSubTotal.setText(iSubTotal);
            jTFTotal.setText(iTotal);
        }
        if (jCmbSelectACar.getSelectedItem().equals("Ford") && jCmbTradeInCar.getSelectedItem().equals("5001 - 20000")){
            Ford = Ford - 2500;
            String iTax = String.format("£ %.2f", cFindTax(Ford + Accessory.GetAmount()));
            String iSubTotal = String.format("£ %.2f", Ford + Accessory.GetAmount());
            String iTotal = String.format("£ %.2f", Ford + Accessory.GetAmount() + cFindTax(Ford + Accessory.GetAmount()));
            jTFTax.setText(iTax);
            jTFSubTotal.setText(iSubTotal);
            jTFTotal.setText(iTotal);
        }
        if (jCmbSelectACar.getSelectedItem().equals("Ford") && jCmbTradeInCar.getSelectedItem().equals("20001 - 50000")){
            Ford = Ford - 2000;
            String iTax = String.format("£ %.2f", cFindTax(Ford + Accessory.GetAmount()));
            String iSubTotal = String.format("£ %.2f", Ford + Accessory.GetAmount());
            String iTotal = String.format("£ %.2f", Ford + Accessory.GetAmount() + cFindTax(Ford + Accessory.GetAmount()));
            jTFTax.setText(iTax);
            jTFSubTotal.setText(iSubTotal);
            jTFTotal.setText(iTotal);
        }
        if (jCmbSelectACar.getSelectedItem().equals("Ford") && jCmbTradeInCar.getSelectedItem().equals("50001 - 100000")){
            Ford = Ford - 1200;
            String iTax = String.format("£ %.2f", cFindTax(Ford + Accessory.GetAmount()));
            String iSubTotal = String.format("£ %.2f", Ford + Accessory.GetAmount());
            String iTotal = String.format("£ %.2f", Ford + Accessory.GetAmount() + cFindTax(Ford + Accessory.GetAmount()));
            jTFTax.setText(iTax);
            jTFSubTotal.setText(iSubTotal);
            jTFTotal.setText(iTotal);
        }
        if (jCmbSelectACar.getSelectedItem().equals("Ford") && jCmbTradeInCar.getSelectedItem().equals("100001 - 500000")){
            Ford = Ford - 250;
            String iTax = String.format("£ %.2f", cFindTax(Ford + Accessory.GetAmount()));
            String iSubTotal = String.format("£ %.2f", Ford + Accessory.GetAmount());
            String iTotal = String.format("£ %.2f", Ford + Accessory.GetAmount() + cFindTax(Ford + Accessory.GetAmount()));
            jTFTax.setText(iTax);
            jTFSubTotal.setText(iSubTotal);
            jTFTotal.setText(iTotal);
        }
        
        //=======================================================BMW================================================================
        if (jCmbSelectACar.getSelectedItem().equals("BMW") && jCmbTradeInCar.getSelectedItem().equals("1 - 5000")){
            BMW = BMW - 5000;
            String iTax = String.format("£ %.2f", cFindTax(BMW + Accessory.GetAmount()));
            String iSubTotal = String.format("£ %.2f", BMW + Accessory.GetAmount());
            String iTotal = String.format("£ %.2f", BMW + Accessory.GetAmount() + cFindTax(BMW + Accessory.GetAmount()));
            jTFTax.setText(iTax);
            jTFSubTotal.setText(iSubTotal);
            jTFTotal.setText(iTotal);
        }
        if (jCmbSelectACar.getSelectedItem().equals("BMW") && jCmbTradeInCar.getSelectedItem().equals("5001 - 20000")){
            BMW = BMW - 2500;
            String iTax = String.format("£ %.2f", cFindTax(BMW + Accessory.GetAmount()));
            String iSubTotal = String.format("£ %.2f", BMW + Accessory.GetAmount());
            String iTotal = String.format("£ %.2f", BMW + Accessory.GetAmount() + cFindTax(BMW + Accessory.GetAmount()));
            jTFTax.setText(iTax);
            jTFSubTotal.setText(iSubTotal);
            jTFTotal.setText(iTotal);
        }
        if (jCmbSelectACar.getSelectedItem().equals("BMW") && jCmbTradeInCar.getSelectedItem().equals("20001 - 50000")){
            BMW = BMW - 2000;
            String iTax = String.format("£ %.2f", cFindTax(BMW + Accessory.GetAmount()));
            String iSubTotal = String.format("£ %.2f", BMW + Accessory.GetAmount());
            String iTotal = String.format("£ %.2f", BMW + Accessory.GetAmount() + cFindTax(BMW + Accessory.GetAmount()));
            jTFTax.setText(iTax);
            jTFSubTotal.setText(iSubTotal);
            jTFTotal.setText(iTotal);
        }
        if (jCmbSelectACar.getSelectedItem().equals("BMW") && jCmbTradeInCar.getSelectedItem().equals("50001 - 100000")){
            BMW = BMW - 1200;
            String iTax = String.format("£ %.2f", cFindTax(BMW + Accessory.GetAmount()));
            String iSubTotal = String.format("£ %.2f", BMW + Accessory.GetAmount());
            String iTotal = String.format("£ %.2f", BMW + Accessory.GetAmount() + cFindTax(BMW + Accessory.GetAmount()));
            jTFTax.setText(iTax);
            jTFSubTotal.setText(iSubTotal);
            jTFTotal.setText(iTotal);
        }
        if (jCmbSelectACar.getSelectedItem().equals("BMW") && jCmbTradeInCar.getSelectedItem().equals("100001 - 500000")){
            BMW = BMW - 250;
            String iTax = String.format("£ %.2f", cFindTax(BMW + Accessory.GetAmount()));
            String iSubTotal = String.format("£ %.2f", BMW + Accessory.GetAmount());
            String iTotal = String.format("£ %.2f", BMW + Accessory.GetAmount() + cFindTax(BMW + Accessory.GetAmount()));
            jTFTax.setText(iTax);
            jTFSubTotal.setText(iSubTotal);
            jTFTotal.setText(iTotal);
        }
        
        //=======================================================Porche================================================================
        if (jCmbSelectACar.getSelectedItem().equals("Porche") && jCmbTradeInCar.getSelectedItem().equals("1 - 5000")){
            Porche = Porche - 5000;
            String iTax = String.format("£ %.2f", cFindTax(Porche + Accessory.GetAmount()));
            String iSubTotal = String.format("£ %.2f", Porche + Accessory.GetAmount());
            String iTotal = String.format("£ %.2f", Porche + Accessory.GetAmount() + cFindTax(Porche + Accessory.GetAmount()));
            jTFTax.setText(iTax);
            jTFSubTotal.setText(iSubTotal);
            jTFTotal.setText(iTotal);
        }
        if (jCmbSelectACar.getSelectedItem().equals("Porche") && jCmbTradeInCar.getSelectedItem().equals("5001 - 20000")){
            Porche = Porche - 2500;
            String iTax = String.format("£ %.2f", cFindTax(Porche + Accessory.GetAmount()));
            String iSubTotal = String.format("£ %.2f", Porche + Accessory.GetAmount());
            String iTotal = String.format("£ %.2f", Porche + Accessory.GetAmount() + cFindTax(Porche + Accessory.GetAmount()));
            jTFTax.setText(iTax);
            jTFSubTotal.setText(iSubTotal);
            jTFTotal.setText(iTotal);
        }
        if (jCmbSelectACar.getSelectedItem().equals("Porche") && jCmbTradeInCar.getSelectedItem().equals("20001 - 50000")){
            Porche = Porche - 2000;
            String iTax = String.format("£ %.2f", cFindTax(Porche + Accessory.GetAmount()));
            String iSubTotal = String.format("£ %.2f", Porche + Accessory.GetAmount());
            String iTotal = String.format("£ %.2f", Porche + Accessory.GetAmount() + cFindTax(Porche + Accessory.GetAmount()));
            jTFTax.setText(iTax);
            jTFSubTotal.setText(iSubTotal);
            jTFTotal.setText(iTotal);
        }
        if (jCmbSelectACar.getSelectedItem().equals("Porche") && jCmbTradeInCar.getSelectedItem().equals("50001 - 100000")){
            Porche = Porche - 1200;
            String iTax = String.format("£ %.2f", cFindTax(Porche + Accessory.GetAmount()));
            String iSubTotal = String.format("£ %.2f", Porche + Accessory.GetAmount());
            String iTotal = String.format("£ %.2f", Porche + Accessory.GetAmount() + cFindTax(Porche + Accessory.GetAmount()));
            jTFTax.setText(iTax);
            jTFSubTotal.setText(iSubTotal);
            jTFTotal.setText(iTotal);
        }
        if (jCmbSelectACar.getSelectedItem().equals("Porche") && jCmbTradeInCar.getSelectedItem().equals("100001 - 500000")){
            Porche = Porche - 250;
            String iTax = String.format("£ %.2f", cFindTax(Porche + Accessory.GetAmount()));
            String iSubTotal = String.format("£ %.2f", Porche + Accessory.GetAmount());
            String iTotal = String.format("£ %.2f", Porche + Accessory.GetAmount() + cFindTax(Porche + Accessory.GetAmount()));
            jTFTax.setText(iTax);
            jTFSubTotal.setText(iSubTotal);
            jTFTotal.setText(iTotal);
        }
        
        //=================================================Aston_Martin===============================================================
        if (jCmbSelectACar.getSelectedItem().equals("Aston_Martin") && jCmbTradeInCar.getSelectedItem().equals("1 - 5000")){
            Aston_Martin = Aston_Martin - 5000;
            String iTax = String.format("£ %.2f", cFindTax(Aston_Martin + Accessory.GetAmount()));
            String iSubTotal = String.format("£ %.2f", Aston_Martin + Accessory.GetAmount());
            String iTotal = String.format("£ %.2f", Aston_Martin + Accessory.GetAmount() + cFindTax(Aston_Martin + Accessory.GetAmount()));
            jTFTax.setText(iTax);
            jTFSubTotal.setText(iSubTotal);
            jTFTotal.setText(iTotal);
        }
        if (jCmbSelectACar.getSelectedItem().equals("Aston_Martin") && jCmbTradeInCar.getSelectedItem().equals("5001 - 20000")){
            Aston_Martin = Aston_Martin - 2500;
            String iTax = String.format("£ %.2f", cFindTax(Aston_Martin + Accessory.GetAmount()));
            String iSubTotal = String.format("£ %.2f", Aston_Martin + Accessory.GetAmount());
            String iTotal = String.format("£ %.2f", Aston_Martin + Accessory.GetAmount() + cFindTax(Aston_Martin + Accessory.GetAmount()));
            jTFTax.setText(iTax);
            jTFSubTotal.setText(iSubTotal);
            jTFTotal.setText(iTotal);
        }
        if (jCmbSelectACar.getSelectedItem().equals("Aston_Martin") && jCmbTradeInCar.getSelectedItem().equals("20001 - 50000")){
            Aston_Martin = Aston_Martin - 2000;
            String iTax = String.format("£ %.2f", cFindTax(Aston_Martin + Accessory.GetAmount()));
            String iSubTotal = String.format("£ %.2f", Aston_Martin + Accessory.GetAmount());
            String iTotal = String.format("£ %.2f", Aston_Martin + Accessory.GetAmount() + cFindTax(Aston_Martin + Accessory.GetAmount()));
            jTFTax.setText(iTax);
            jTFSubTotal.setText(iSubTotal);
            jTFTotal.setText(iTotal);
        }
        if (jCmbSelectACar.getSelectedItem().equals("Aston_Martin") && jCmbTradeInCar.getSelectedItem().equals("50001 - 100000")){
            Aston_Martin = Aston_Martin - 1200;
            String iTax = String.format("£ %.2f", cFindTax(Aston_Martin + Accessory.GetAmount()));
            String iSubTotal = String.format("£ %.2f", Aston_Martin + Accessory.GetAmount());
            String iTotal = String.format("£ %.2f", Aston_Martin + Accessory.GetAmount() + cFindTax(Aston_Martin + Accessory.GetAmount()));
            jTFTax.setText(iTax);
            jTFSubTotal.setText(iSubTotal);
            jTFTotal.setText(iTotal);
        }
        if (jCmbSelectACar.getSelectedItem().equals("Aston_Martin") && jCmbTradeInCar.getSelectedItem().equals("100001 - 500000")){
            Aston_Martin = Aston_Martin - 250;
            String iTax = String.format("£ %.2f", cFindTax(Aston_Martin + Accessory.GetAmount()));
            String iSubTotal = String.format("£ %.2f", Aston_Martin + Accessory.GetAmount());
            String iTotal = String.format("£ %.2f", Aston_Martin + Accessory.GetAmount() + cFindTax(Aston_Martin + Accessory.GetAmount()));
            jTFTax.setText(iTax);
            jTFSubTotal.setText(iSubTotal);
            jTFTotal.setText(iTotal);
        }
        
        String jenkel = "";
        
        if(jRadioPria.isSelected()){
            jenkel = jRadioPria.getText();
        }
        else if(jRadioWanita.isSelected()){
            jenkel = jRadioWanita.getText();
        }
        
//        =================================================================Calender=====================================================
        Calendar kalender = new GregorianCalendar();
        int year = kalender.get(Calendar.YEAR);
        int month = kalender.get(Calendar.MONTH)+1;
        int day = kalender.get(Calendar.DAY_OF_MONTH);
        int hour = kalender.get(Calendar.HOUR_OF_DAY);
        int minute = kalender.get(Calendar.MINUTE);
        int second = kalender.get(Calendar.SECOND);
        
        String start = year + " / " + month + " / " + day;
        String time = hour +" : "+ minute +" : "+ second;
        
        jTxtKalender.setText(start);
        jTxtJam.setText(time);
        //===========================================================Receipt===============================================================
        jReceipt.append("\t            Car Dealer Management System" + "\n");
        jReceipt.append(jTxtKalender.getText()+"\t\t\t                   "+jTxtJam.getText());
        jReceipt.append("\n-------------------------------------------------------------------------------------------------"+"\n");
        jReceipt.append("Nomor KTP" + "\t\t\t" + jTFCustomerID.getText() + "\n");
        jReceipt.append("Nama Lengkap" + "\t\t\t" + jTFFristname.getText() + "\n");
        jReceipt.append("Jenis Kelamin" + "\t\t\t" + jenkel+ "\n");
        jReceipt.append("Tanggal Lahir" + "\t\t\t" + jCalendarCombo1.getSelectedItem()+ "\n");
        jReceipt.append("Alamat" + "\t\t\t" + jTFAddress.getText() + "\n");
        jReceipt.append("Kode Pos" + "\t\t\t" + jTFPostCode.getText() + "\n");
        jReceipt.append("Pekerjaan" + "\t\t\t" + jPekerjaan.getSelectedItem()+ "\n");
        jReceipt.append("Kota" + "\t\t\t" + jTFTown.getText() + "\n");
        jReceipt.append("-------------------------------------------------------------------------------------------------"+"\n");
        jReceipt.append("Tanggal Beli" + "\t\t\t" + jTFTown.getText() + "\n");
        jReceipt.append("Jenis Mobil" + "\t\t\t" + jCmbSelectACar.getSelectedItem()+ "\n");
        jReceipt.append("Tahun" + "\t\t\t" + jSelectaCarYear.getText() + "\n");
        jReceipt.append("Harga" + "\t\t\t" + jSelectaCarCost.getText() + "\n");
        jReceipt.append("-------------------------------------------------------------------------------------------------"+"\n");
        jReceipt.append("Jenis Mobil" + "\t\t\t" + jCmbTradeInCar.getSelectedItem()+ "\n");
        jReceipt.append("Tahun" + "\t\t\t" + jTxfTradeInCarYear.getText() + "\n");
        jReceipt.append("Harga" + "\t\t\t" + jTxfTradeInCarCost.getText() + "\n");
        jReceipt.append("-------------------------------------------------------------------------------------------------"+"\n");
        jReceipt.append("Pajak" + "\t\t\t" + jTFTax.getText() + "\n");
        jReceipt.append("Sub Total" + "\t\t\t" + jTFSubTotal.getText() + "\n");
        jReceipt.append("Total" + "\t\t\t" + jTFTotal.getText() + "\n");
    }//GEN-LAST:event_jBtnTotalActionPerformed

    private void jTxfTradeInCarYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxfTradeInCarYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxfTradeInCarYearActionPerformed

    private void jCalendarCombo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCalendarCombo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCalendarCombo1ActionPerformed

    private void jRadioPriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioPriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioPriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tampilan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tampilan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tampilan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tampilan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tampilan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JenisKelamin;
    private javax.swing.JLabel Pekerjaan;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jAddress1;
    private javax.swing.JButton jBtnExit;
    private javax.swing.JButton jBtnPrint;
    private javax.swing.JButton jBtnReset;
    private javax.swing.JButton jBtnTotal;
    private org.freixas.jcalendar.JCalendarCombo jCalendarCombo1;
    private javax.swing.JCheckBox jCbkLeatherInterior;
    private javax.swing.JCheckBox jCbkModified;
    private javax.swing.JCheckBox jCbkStandard;
    private javax.swing.JCheckBox jCbkStereoSystem;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JComboBox jCmbSelectACar;
    private javax.swing.JComboBox jCmbTradeInCar;
    private javax.swing.JLabel jCustomerID;
    private javax.swing.JLabel jFirstName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelTitle;
    private javax.swing.JComboBox jPekerjaan;
    private javax.swing.JLabel jPostCode;
    private javax.swing.JRadioButton jRadioPria;
    private javax.swing.JRadioButton jRadioWanita;
    private javax.swing.JTextArea jReceipt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jSelectaCarCost;
    private javax.swing.JTextField jSelectaCarYear;
    private javax.swing.JTextField jTFAddress;
    private javax.swing.JTextField jTFCustomerID;
    private javax.swing.JTextField jTFFristname;
    private javax.swing.JTextField jTFPostCode;
    private javax.swing.JTextField jTFSubTotal;
    private javax.swing.JTextField jTFTax;
    private javax.swing.JTextField jTFTotal;
    private javax.swing.JTextField jTFTown;
    private javax.swing.JLabel jTown;
    private javax.swing.JTextField jTxfTradeInCarCost;
    private javax.swing.JTextField jTxfTradeInCarYear;
    private javax.swing.JTextField jTxtJam;
    private javax.swing.JTextField jTxtKalender;
    private javax.swing.JLabel tanggal;
    // End of variables declaration//GEN-END:variables
}
